services:
  auth-service:
    build:
      context: .
      args:
        - GITHUB_USERNAME=${GITHUB_USERNAME}
        - GITHUB_TOKEN=${GITHUB_TOKEN}
    ports:
      - "8080:8080"
    env_file:
      - .env